### ISSUE TITLE
Error printing to console should be optional

### ISSUE THREAD

**Issue by sielay** [krasimir/atomus#4]
https://github.com/krasimir/atomus/blob/10487b4563172fe68e63de56d0a76c8659e7ad2b/lib/index.js#L46

This line shouldn't happen by default. It spoils output while using in tests.

**Comment by krasimir** [comment]
Well, isn't it that helpful. I mean knowing that you have errors on your page.

**Comment by sielay** [comment]
It is, but as optional. You should have a choice first to choose a way how you handle them. Then if you use that in continous integration tools it spoils output data.

**Comment by krasimir** [comment]
`1.0.1` version is released. It's not printing those errors by default anymore.

**Comment by sielay** [comment]
Awesome. Thanks
